apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: agenttypes.agents.example.com
spec:
  group: agents.example.com
  names:
    kind: AgentType
    plural: agenttypes
    singular: agenttype
    shortNames:
      - at
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              required: ["agent"]
              properties:
                agent:
                  type: object
                  required: ["image"]
                  properties:
                    image:
                      type: string
                    name:
                      type: string
                      default: "agent"
                    environment:
                      type: object
                      properties:
                        variables:
                          type: array
                          items:
                            type: object
                            required: ["name", "value"]
                            properties:
                              name:
                                type: string
                              value:
                                type: string
                        sdk:
                          type: object
                          properties:
                            runtime:
                              type: string
                              enum: ["python", "nodejs"]
                            version:
                              type: string
                            packages:
                              type: array
                              items:
                                type: string
                        glueCode:
                          type: object
                          properties:
                            source:
                              type: string
            status:
              type: object
              properties:
                phase:
                  type: string
                message:
                  type: string
      additionalPrinterColumns:
        - name: Status
          type: string
          jsonPath: .status.phase
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp