apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-operator
  namespace: default
  labels:
    app: agent-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-operator
  template:
    metadata:
      labels:
        app: agent-operator
    spec:
      serviceAccountName: agent-operator
      containers:
      - name: operator
        image: agent-operator:latest
        imagePullPolicy: Never  # For local development 