---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: agent-operator
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["agents.example.com"]
  resources: ["agenttypes"]
  verbs: ["get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agent-operator
  namespace: default
subjects:
- kind: ServiceAccount
  name: agent-operator
  namespace: default
roleRef:
  kind: Role
  name: agent-operator
  apiGroup: rbac.authorization.k8s.io 