apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-operator
  template:
    metadata:
      labels:
        app: agent-operator
    spec:
      serviceAccountName: agent-operator
      containers:
      - name: operator
        image: agent-operator
        env:
        - name: KOPF_NAMESPACE
          value: "*"
        - name: KOPF_RUN_MODE
          value: "cluster"
